site_name: La Caffetiera
nav:
    - Software:
        - Software.md
    - Datos:
        - Datos.md
    - Documentación:
        - Documentación.md
    - Clases: 
        - CLASE 12/03: CLASE_12-03.md
        - CLASE 21/03: CLASE_21-03.md
        - CLASE 24/03: CLASE_24-03.md
        - CLASE 27/03: CLASE_27-03.md
        - CLASE 30/03: CLASE_30-03.md
        - CLASE 13/04: CLASE_13-04.md
        - CLASE 16/04: CLASE_16-04.md
        - CLASE 20/04: CLASE_20-04.md
        - CLASE 23/04: CLASE_23-04.md
        - CLASE 27/04: CLASE_27-04.md
        - CLASE 11/05: CLASE_11-05.md
theme:
    name: readthedocs
